[build]
  functions = "functions"
  command = "netlify link && netlify build && netlify deploy"
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
[functions]
  node_bundler = "esbuild"
  external_node_modules = ["express"]